name: run unit tests of feature branches

on:
  push:
    branches:
      - 'feature/*'

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run unit tests
        run: mvn test

     
      
   
   
